<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>footer_version_number</name>
   <tag></tag>
   <elementGuidId>58b38fb1-1190-4920-88f7-04a1e175964a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='footer'][contains(text(),'OrangeHRM')]/text()[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='footer'][contains(text(),'OrangeHRM')]/*[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='footer'][contains(text(),'OrangeHRM')]/*[1]</value>
   </webElementProperties>
</WebElementEntity>
