<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>user_nav_admin_menu</name>
   <tag></tag>
   <elementGuidId>c1920d8b-9c56-4fc3-9113-caffac033903</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='mainMenu']//b[contains(text(),'Admin')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='mainMenu']//b[contains(text(),'Admin')]</value>
   </webElementProperties>
</WebElementEntity>
