<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>user_nav_recruitment_menu</name>
   <tag></tag>
   <elementGuidId>de9ceed8-de3b-43b0-8321-a77c4b5a8400</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='mainMenu']//b[contains(text(),'Recruitment')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='mainMenu']//b[contains(text(),'Recruitment')]</value>
   </webElementProperties>
</WebElementEntity>
