<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>user_nav_dashboard_menu</name>
   <tag></tag>
   <elementGuidId>9cde059e-91fb-4cf9-a4d9-ed701ce551fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='mainMenu']//b[contains(text(),'Dashboard')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='mainMenu']//b[contains(text(),'Dashboard')]</value>
   </webElementProperties>
</WebElementEntity>
