<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>user_nav_buzz_menu</name>
   <tag></tag>
   <elementGuidId>d4c6762e-6d4f-4e83-9541-9925f5a84993</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='mainMenu']//b[contains(text(),'Buzz')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='mainMenu']//b[contains(text(),'Buzz')]</value>
   </webElementProperties>
</WebElementEntity>
